// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljbqpqtbotbsdaltubmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqYnFwcXRib3Ric2RhbHR1Ym1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTY3MjMsImV4cCI6MjA1Njg5MjcyM30.HwJzo_WpHo7WYzVACgNNBxVkMw2DvR4adYXzPUYs9RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);